### ISSUE TITLE
jxl-color: Attempt to multiply with overflow at ICC tagstart

### ISSUE THREAD

**Issue by EugeneVert** [tirr-c/jxl-oxide#123]
https://github.com/tirr-c/jxl-oxide/blob/f3e4aa9877fd5b995aa2c565fe2e2307264676f8/crates/jxl-color/src/icc.rs#L199-L206

![ICC_tag_list_tagsize](https://github.com/tirr-c/jxl-oxide/assets/69643766/14050e6d-9665-439a-997b-830b9176a699)

```log
thread 'main' panicked at crates/jxl-color/src/icc.rs:204:33:
attempt to multiply with overflow
```

Libjxl uses u64 `num_tags`, `tagstart` and `tagsize` but writes output as a big endian unsigned 32-bit integer

**Comment by tirr-c** [comment]
If `num_tags * 12` overflows, the output ICC profile size should be larger than `u32::MAX` bytes so it's already invalid. Let me figure out where should the check go.
