### ISSUE TITLE
Overflow in `add_log2_ceil` during during `read_permutation`

### ISSUE THREAD

**Issue by EugeneVert** [tirr-c/jxl-oxide#130]
Overflow during Toc parsing in `read_permutation->read_varint->add_log2_ceil->(x + 1)`
https://github.com/tirr-c/jxl-oxide/blob/fb2642837786df0f2b90ada4664140364ae181f6/crates/jxl-frame/src/data/toc.rs#L195-L201
https://github.com/tirr-c/jxl-oxide/blob/2e691840eac974f149f9c4cedbf1ba1529e0477c/crates/jxl-coding/src/permutation.rs#L17-L20
https://github.com/tirr-c/jxl-oxide/blob/fb2642837786df0f2b90ada4664140364ae181f6/crates/jxl-coding/src/lib.rs#L619-L621

![read_permutation_overflow](https://github.com/tirr-c/jxl-oxide/assets/69643766/a293cd66-13f8-404c-acb4-ac66b9771eb4)

```log
thread 'main' panicked at /rustc/.../library/core/src/num/mod.rs:1142:5:
attempt to add with overflow
```

**Comment by EugeneVert** [comment]
This panic debug build only, i wonder why fuzzer is complaining about it

**Comment by tirr-c** [comment]
The fuzzer is configured to add overflow checks, that's why.
