### ISSUE TITLE
Can't find `JxlImage::renderer` 

### ISSUE THREAD

**Issue by damywise** [tirr-c/jxl-oxide#139]
Heya, I've never touched Rust so forgive if newbie question. Also I can't find discussion/community either so I'm asking here.

I can't find anything in the repo nor even reference the `image.renderer` as mentioned [here](https://github.com/tirr-c/jxl-oxide/tree/main/crates/jxl-oxide#decoding-an-image).

How do I get that?

**Comment by tirr-c** [comment]
Oops, maybe I've only updated docs in the source code; sorry for the confusion! The decoding API has been changed in 0.5.0. Please see https://docs.rs/jxl-oxide/latest/jxl_oxide/ for updated usage.

**Comment by tirr-c** [comment]
Yep, it's an example that assumes a stream that returns byte buffers.

**Comment by damywise** [comment]
Got it, thanks again!
