### ISSUE TITLE
Unbounded memory usage (over 16GB) on a crafted image, bypassing allocation tracking

### ISSUE THREAD

**Issue by Shnatsel** [tirr-c/jxl-oxide#165]
Decoding this image causes a steadily increasing memory usage: [oom-97a147dae72d761a921774a317f89d1d799654ff.jxl.gz](https://github.com/tirr-c/jxl-oxide/files/13815216/oom-97a147dae72d761a921774a317f89d1d799654ff.jxl.gz) 
I have killed it the process once it consumed 16GB.

This was found by `cargo fuzz` using a fuzzing harness identical to the in-tree one, so it sets `.alloc_tracker(AllocTracker::with_limit(128 * 1024 * 1024)) // 128 MiB` which appears to be ineffective.

Tested on commit b1115f987e2ca269ca903e6726e04a74db703438

**Comment by tirr-c** [comment]
Maybe some missing checks are causing a loop somewhere? Will take a look with #163 later today.
