### ISSUE TITLE
Isobmff-based containers unsupported

### ISSUE THREAD

**Issue by GageBerz** [tirr-c/jxl-oxide#17]
Occurs when loading .jxl files that have isobmff-based containers. Does not occur with naked codestreams.

[1.zip](https://github.com/tirr-c/jxl-oxide/files/11470102/1.zip)
Code where it complains:
`
let result = render
        .load_until_keyframe(bitstream, progressive, region)
        .expect("failed to load frames");
`
Error:
`thread '<unnamed>' panicked at 'failed to load frames: Frame(Bitstream(NonZeroPadding))', src/decoder/formats/jxl.rs:139:10`

**Comment by GageBerz** [comment]
If we don't panic at the error and let the program keep going, this is the result.
[t.txt](https://github.com/tirr-c/jxl-oxide/files/11472247/t.txt)

**Comment by EugeneVert** [comment]
Please check if you use `jxl_bitstream::Bitstream::new_detect` rather than `jxl_bitstream::Bitstream::new`, since the latter is used for bare codestream.

**Comment by GageBerz** [comment]
I am using new_detect

**Comment by GageBerz** [comment]
Apparently I fixed whatever the issue was since between now and when I opened the issue. Not sure what did it though.
