### ISSUE TITLE
Tiny crafted files take 15 seconds to decode, exceed memory limits

### ISSUE THREAD

**Issue by Shnatsel** [tirr-c/jxl-oxide#170]
Here are the 10 worst offenders:
[jxl-timeouts-round2.tar.gz](https://github.com/tirr-c/jxl-oxide/files/13820801/jxl-timeouts-round2.tar.gz)

They also take at around 1GB of RAM to decode, while the fuzzing harness specifies a 128Mb memory limit.

This occurs even with the fixes for #163 and #165 applied.

Found with `cargo fuzz`. Tested on commit 362447b051e4402b0b10fd9cc9fc48ac2156b139

**Comment by tirr-c** [comment]
`timeout-2b72930122d3e999ff9efb4733e499da2ab8abb7` will be fixed by #171. The other samples need more investigation; djxl crashes on aarch64 and *occasionally* crashes on x86_64. I guess it needs to be reported to libjxl also.
