### ISSUE TITLE
Small crafted files take over 10 seconds to decode

### ISSUE THREAD

**Issue by Shnatsel** [tirr-c/jxl-oxide#179]
These files were found by cargo-fuzz. They take a disproportionately long time to decode, up to 10 seconds for files of under 2 kilobytes. This slows down fuzzing, and there could be some DoS potential here.

[jxl-long-decode-times.tar.gz](https://github.com/tirr-c/jxl-oxide/files/13881473/jxl-long-decode-times.tar.gz)

Tested on commit 9704179c079c73fdba06fd138426a21e02158db5

**Comment by tirr-c** [comment]
The root cause of slow decoding is large MA trees (#170, mitigrated by #173). jxl-oxide CLI exits immediately with error when I set `--approx-memory-limit`, so it might be a problem with fuzzing harness. I'll take a look later today.

**Comment by tirr-c** [comment]
It turns out that MA tree limit (proportional to the number of decoded samples) is applied too late. I moved those checks into MA tree decoding in #180.
