### ISSUE TITLE
Fuzzing crash: OOB in jxl-coding

### ISSUE THREAD

**Issue by hackerbirds** [tirr-c/jxl-oxide#216]
Hello,

I'm repeatedly finding this crash early on when fuzzing.

I can't upload the test case file right now on Github sorry, but here is how you can retrieve it: the file encoded in base64 is `/wr/CscOKyT///8KW0EKQQSU`. Running `base64 -d <<< "/wr/CscOKyT///8KW0EKQQSU" > file.jxl` on Linux should be able to decode the file. The Sha256 hash to check is `1c2e5cca8df7f2ad03b50207e5336d3040354f2a052a6303bb160a2eef5640df`

Here is the crash (I'm on the latest commit `0c9c71e`) :

```
Running: artifacts/libfuzzer-decode/minimized-from-282597921e1c5f4d8b6c684d0f0c5d1d6bb53bc5
thread '<unnamed>' panicked at /home/user/Documents/jxl-oxide/crates/jxl-coding/src/lib.rs:491:33:
index out of bounds: the len is 0 but the index is 0
```

Let me know if you are able to reproduce it or if you need help with retrieving the test file.

**Comment by tirr-c** [comment]
Thanks for reporting! I can reproduce it, seems like it's caused by invalid LZ77 stream.
