### ISSUE TITLE
Fuzz: Add overflow in jxl-modular

### ISSUE THREAD

**Issue by hackerbirds** [tirr-c/jxl-oxide#219]
Hello, I found another crash. It still crashes for me as of the latest commit `d1f9a87`.

Test case: 
[minimized-from-ac4e0458dc5196d300b5c5335240d24465a8d796.zip](https://github.com/tirr-c/jxl-oxide/files/14209775/minimized-from-ac4e0458dc5196d300b5c5335240d24465a8d796.zip)

Crash log:
```
Running: fuzz/artifacts/libfuzzer-decode/minimized-from-ac4e0458dc5196d300b5c5335240d24465a8d796
thread '<unnamed>' panicked at /home/user/Documents/jxl-oxide/crates/jxl-modular/src/image.rs:774:35:
attempt to add with overflow
```

**Comment by tirr-c** [comment]
It seems that the integer overflow is fixed in #227 (7fa6e9e43fdeb2f112996c4161fbdd174b579633). (Wrapping arithmetic in Modular image decoding is fine and intended.)
