### ISSUE TITLE
"Explicit panic" in `jxl-modular/src/image.rs:257:17` on crafted input

### ISSUE THREAD

**Issue by Shnatsel** [tirr-c/jxl-oxide#247]
File to trigger it: [crash-9955bcf8182b1cd5457867f61ad5151809698652.jxl.gz](https://github.com/tirr-c/jxl-oxide/files/14383489/crash-9955bcf8182b1cd5457867f61ad5151809698652.jxl.gz)

Tested on commit 72b0f8c57ff7f01579deb59924f9cca6dea41d39

I think I spoke too soon about there being no more panics :sweat_smile:

**Comment by tirr-c** [comment]
Uh... could you check if it panics on PR #246?
