### ISSUE TITLE
Reject invalid bitstreams

### ISSUE THREAD

**Issue by EugeneVert** [tirr-c/jxl-oxide#25]
Currently, some incorrect bitstreams can lead to panics.

Crashes found using afl with https://github.com/libjxl/testdata/tree/main/oss-fuzz input:
[crashes.zip](https://github.com/tirr-c/jxl-oxide/files/11579165/crashes.zip)
(Only --release panics)

- [x] ans.rs:92:21 https://github.com/tirr-c/jxl-oxide/pull/29
- [x] blend.rs:176:13 https://github.com/tirr-c/jxl-oxide/pull/37
- [x] blend.rs:390:71 https://github.com/tirr-c/jxl-oxide/pull/30
- [x] blend.rs:401:72 https://github.com/tirr-c/jxl-oxide/pull/30
- [x] gabor.rs:13:30 https://github.com/tirr-c/jxl-oxide/pull/38
- [x] hf_metadata.rs:119:71 https://github.com/tirr-c/jxl-oxide/pull/40
- [x] icc.rs:158:18 https://github.com/tirr-c/jxl-oxide/pull/39
- [x] icc.rs:222:49 https://github.com/tirr-c/jxl-oxide/pull/39
- [x] inner.rs:432:29
- [x] lib.rs:389:9 https://github.com/tirr-c/jxl-oxide/pull/38
- [x] transform.rs:449:9 AND transform.rs:489:9
- [x] upsampling.rs:132:34 https://github.com/tirr-c/jxl-oxide/pull/30

**Comment by EugeneVert** [comment]
[Frame header parsing](https://github.com/tirr-c/jxl-oxide/blob/d5cdaf84e34392735cc99d2094e6d2e9f430ea95/crates/jxl-frame/src/lib.rs#L81) is missing some checks from spec
see also: [libjxl's frame_header.cc](https://github.com/libjxl/libjxl/blob/main/lib/jxl/frame_header.cc)

**Comment by tirr-c** [comment]
For `transform.rs`: is it from `jxl-modular`? It shouldn't cause any problem, as long as channel list transform is not broken. Maybe the channel list transform misbehaves when Squeeze params are set to nonsense values.

**Comment by EugeneVert** [comment]
Yes, `transform.rs` is from modular. it panics on assertion when transform is performed on non-equal-sized channels

**Comment by EugeneVert** [comment]
libjxl returns `CheckEqualChannels` error on these samples
```bash
./lib/jxl/modular/transform/palette.cc:155: JXL_RETURN_IF_ERROR code=1: CheckEqualChannels(input, begin_c, end_c)
./lib/jxl/modular/encoding/encoding.cc:474: JXL_RETURN_IF_ERROR code=1: transform.MetaApply(image)
./lib/jxl/modular/encoding/encoding.cc:597: JXL_RETURN_IF_ERROR code=1: dec_status
```

**Comment by tirr-c** [comment]
Fuzzer is being run periodically, and most of the findings are fixed now. Closing!
