### ISSUE TITLE
Lossless JPEG-XL files encoded with effort 8 or 9 sometimes fail to decode.

### ISSUE THREAD

**Issue by Aerocatia** [tirr-c/jxl-oxide#268]
This image encoded with cjxl 0.10.1 fails to decode with jxl-oxide, giving the error `frame error: modular stream error: entropy decoder error: error from bitstream: I/O error: unexpected end of file`.
File: [1225036754354229250_1.zip](https://github.com/tirr-c/jxl-oxide/files/14467774/1225036754354229250_1.zip)

If it is encoded with `-e 7` it works fine.

I have no idea what is so special about this image, it was just part of a set of images that is having issues with libjxl.
There seems to be a bug with lossless compression on libjxl's side, as some images fail to encode at all.

Despite all of this the sample decodes with djxl.

**Comment by Aerocatia** [comment]
Another sample, this one gives `Error: Failed to process 1070025136848351232_1.bitmap: frame error: modular stream error: entropy decoder error: ANS stream verification failed`.

Again, efforts <8 do not produce a file that fails in jxl-oxide.

[1070025136848351232_1.zip](https://github.com/tirr-c/jxl-oxide/files/14467830/1070025136848351232_1.zip)

**Comment by tirr-c** [comment]
I force decoded the first image with error checks off and got this. Maybe this is caused by #227, will bisect when I have more time.

![out](https://github.com/tirr-c/jxl-oxide/assets/2322996/e0c39cae-e9c1-4189-9c99-a93923001e18)

**Comment by tirr-c** [comment]
Turns out that it has been broken since v0.1.0. I'm going to investigate this, maybe it'll take a while though...

**Comment by tirr-c** [comment]
There was an unfortunate mistake in libjxl that doesn't quite follow the spec and misses better compression. We need to workaround and match libjxl here...
