### ISSUE TITLE
Pixels of incorrect color in lossless encoded images

### ISSUE THREAD

**Issue by jendalinda** [tirr-c/jxl-oxide#311]
jxl-oxide v0.8.0
Some losslessly encoded jxl files are decoded incorrectly by jxl-oxide. libjxl decodes these files correctly.

Pixels alongside the black contour are supposed to be gray.

![error](https://github.com/user-attachments/assets/63ed001b-a768-4aeb-b534-a50708292d8b)

Here are some of the affected jxl files:
[pack.zip](https://github.com/user-attachments/files/16398645/pack.zip)

**Comment by tirr-c** [comment]
Thanks for reporting! I was able to reproduce this.

Both images use non-trivial palette lookups, so maybe it's a bug in inverse palette.
