### ISSUE TITLE
Collect code coverage

### ISSUE THREAD

**Issue by tirr-c** [tirr-c/jxl-oxide#55]
Consider collecting coverage info during tests and uploading it somewhere. This will help finding areas not tested by current test suite in jxl-oxide.

**Comment by saschanaz** [comment]
Ran the coverage with:

```sh
CARGO_INCREMENTAL=0 RUSTFLAGS='-Cinstrument-coverage' LLVM_PROFILE_FILE='cargo-test-%p-%m.profraw' cargo test
grcov . --binary-path ./target/debug/deps/ -s . -t html --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/html
```

and got the coverage:

![image](https://github.com/tirr-c/jxl-oxide/assets/3396686/eb56d781-8f91-4698-b758-d9de42e95174)

It would indeed be great to share this in some way (e.g. Codecov?) and encourage contributions on this.
