### ISSUE TITLE
Cannot decode each frame of animated images on demand

### ISSUE THREAD

**Issue by saschanaz** [tirr-c/jxl-oxide#64]
In https://github.com/saschanaz/jxl-winthumb I did the migration from libjxl to jxl-oxide. Thanks for making this project!

One thing I found is that it's hard to let an object have a JxlRenderer member because its lifetime depends on the parent JxlImage. The purpose is to let the object decode each frame on demand (because the consumer may not need the whole frames, e.g. when rendering a thumbnail), but I couldn't do that because I could not save JxlRenderer itself to save the decode progress.

Is there any good way for that?

**Comment by tirr-c** [comment]
I'm on the way of improving decoding process and interfaces, which includes removing lifetime parameters. Stay tuned!

**Comment by tirr-c** [comment]
Lifetime parameter is no longer needed since jxl-oxide 0.4.0. It should be easier to defer rendering; could you try it and tell how it feels?

**Comment by saschanaz** [comment]
I'll try it next week, thanks!

**Comment by saschanaz** [comment]
Finally got some time to try the new version, and it fits nicely!

... except it somehow still takes some time to initialize. To match the target API constrain that requires the frame count before actual rendering, I currently run a loop with `load_next_frame()` until it reaches the end to get the count and then later call `render_next_frame()`, is this the right use of this library?

**Comment by tirr-c** [comment]
Yeah, it's `load_next_frame()` and then `render_frame(keyframe_idx)`. It shouldn't take too much time loading all frames though; all it does is to decode frame header and buffer rest of the frame. `jxl-info` does exactly this, so you can compare the loading time with `jxl-info`. If it's also slow, let me know!

**Comment by saschanaz** [comment]
For now I'll close this; thank you for your help!
